
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:8888']
        - job_name: node
          scrape_interval: 5s
          static_configs:
          - targets: ['localhost:9100']

processors:
  batch:
exporters:
  debug:
    verbosity: detailed
  file/traces:
    path: ./traces_logs.json
    rotation:
      max_megabytes: 1
      max_backups: 3
  file/metrics:
    path: ./metrics_logs.json
    rotation:
      max_megabytes: 1
      max_backups: 3
  otlphttp:
    endpoint: http://host.docker.internal:6378
    tls:
      insecure: true
    compression: none

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [debug,otlphttp,file/metrics]

